
(()=>{
const root=document.getElementById('budget-dough-reports'),$=s=>root.querySelector(s),money=n=>(n/100).toLocaleString('zh-CN',{maximumFractionDigits:2}),key='rouqian-web-v1:'+location.pathname.replace(/index\.html$/, '');
const initial=()=>({cycle:'month',total:100000,cats:[{id:'pool',name:'待分配',budget:100000,spent:0,color:'#d4d4bc'}],history:[],deleted:[],archives:[],period:new Date().getFullYear()+'-'+String(new Date().getMonth()+1).padStart(2,'0')});
let state=initial(),selected=null,cut=5000,previous=null,drag=null,canStore=true,draft=null,deleting=null,reportIndex=null,storageBlocked=false;
try{const raw=localStorage.getItem(key);if(raw){const p=JSON.parse(raw);validateData(p);state=p;}}catch(e){canStore=false;storageBlocked=true;}
state.deleted ||= [];state.archives ||= [];state.period ||= '2026-09';state.transactions ||= [];state.archives.forEach(p=>{p.transactions ||= [];p.deleted ||= [];});
const esc=v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const cat=id=>state.cats.find(c=>c.id===id),available=c=>c.budget-c.spent;
const cents=v=>/^\d+(\.\d{1,2})?$/.test(String(v).trim())?Math.round(Number(v)*100):NaN,safe=v=>Number.isSafeInteger(v)&&v>0;
function save(){if(storageBlocked){$('#bd-storage').textContent='本机旧数据无法读取，暂不覆盖。请先保留原始数据或恢复正确备份。';return;}try{localStorage.setItem(key,JSON.stringify(state));canStore=true;}catch{canStore=false;}$('#bd-storage').textContent=canStore?'已保存在此设备 · 不会上传账单':'本机保存失败，请立即导出备份；关闭页面可能丢失更改';}
function notice(t,undo=false){const n=$('#bd-notice');n.textContent=t;if(undo){const b=document.createElement('button');b.textContent='撤销';b.onclick=()=>{if(previous){state=previous;previous=null;selected=null;render();save();notice('已撤销上一步');}};n.append(b);}}
function checkpoint(){if(storageBlocked)throw Error('请先恢复有效备份再修改账本');previous=JSON.parse(JSON.stringify(state));}
function log(t){state.history.unshift(t);}
function render(){
const spent=state.cats.reduce((a,c)=>a+c.spent,0)+state.deleted.reduce((a,c)=>a+c.spent,0);$('#bd-balance').textContent=money(state.total-spent);$('#bd-period').textContent=state.period+' · 可用预算';$('#bd-summary').textContent=`总预算 ¥${money(state.total)} · 已花 ¥${money(spent)}`;
const max=Math.max(...state.cats.map(c=>c.budget),100),host=$('#bd-buckets');host.innerHTML='';
state.cats.forEach(c=>{const chosen=selected===c.id,section=document.createElement('section');section.className='bucket'+(chosen?' source':'');section.dataset.id=c.id;section.style.setProperty('--clay',c.color);const width=c.budget/max*100;
section.innerHTML=`<div class="row"><span class="name">${esc(c.name)}</span><span class="amount">¥${money(c.budget)}</span></div><div class="track"><div class="dough" style="width:${width}%"><div class="spent" style="width:${c.budget?c.spent/c.budget*100:0}%"></div>${chosen?`<div class="cutmark" style="left:${(c.budget-cut)/c.budget*100}%"></div>`:''}</div></div><div class="under"><span>已花 ¥${money(c.spent)} · 剩余 ¥${money(available(c))}</span>${c.id!=='pool'?`<button type="button" data-delete="${c.id}" aria-label="删除${esc(c.name)}">删除</button>`:''}<button type="button" class="cursor-interaction" data-cut="${c.id}" ${available(c)<=0?'disabled':''}>${chosen?'收起': '切一块'}</button></div>`;
if(chosen){const box=document.createElement('div');box.className='cutbox';box.innerHTML=`<div class="row"><label for="bd-cutvalue">切出金额 ¥</label><input id="bd-cutvalue" type="number" min="0.01" step="0.01" max="${available(c)/100}" value="${cut/100}" inputmode="decimal"></div><input id="bd-slider" aria-label="调整切分金额" type="range" min="1" max="${available(c)}" step="1" value="${cut}"><div class="dragrow"><button class="piece cursor-interaction" type="button" aria-label="拖动切出的预算">¥${money(cut)}</button><span class="micro">拖到另一分类<br>或点选下方目标</span></div><select id="bd-destination" aria-label="转入分类" style="width:100%;padding:8px;margin-top:8px;border-radius:8px;background:var(--paper)"><option value="">选择转入分类…</option>${state.cats.filter(x=>x.id!==c.id).map(x=>`<option value="${x.id}">${esc(x.name)}</option>`).join('')}</select>`;section.append(box);}
host.append(section);
let timer,start;const track=section.querySelector('.track');track.onpointerdown=e=>{start={x:e.clientX,y:e.clientY};timer=setTimeout(()=>select(c.id),400);};track.onpointermove=e=>{if(start&&Math.hypot(e.clientX-start.x,e.clientY-start.y)>8)clearTimeout(timer);};['pointerup','pointercancel','pointerleave'].forEach(k=>track.addEventListener(k,()=>clearTimeout(timer)));
});
host.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>openDelete(b.dataset.delete));
host.querySelectorAll('[data-cut]').forEach(b=>b.onclick=()=>select(b.dataset.cut));
if(selected){$('#bd-cutvalue').oninput=e=>updateCut(cents(e.target.value));$('#bd-slider').oninput=e=>updateCut(Number(e.target.value));$('#bd-destination').onchange=e=>{if(e.target.value)transfer(e.target.value);};$('.piece').onpointerdown=startDrag;}
$('#bd-history').innerHTML='';for(const t of state.history){const el=document.createElement('div');el.className='ledger';el.textContent=t;$('#bd-history').append(el);}if(!state.history.length)$('#bd-history').textContent='还没有操作记录';
$('#bd-archivedspent').textContent=state.deleted.length?'已删除项目的支出 ¥'+money(state.deleted.reduce((a,c)=>a+c.spent,0))+'（仍计入本期已花）':'';
$('#bd-periodhistory').innerHTML='';for(const a of state.archives){const d=document.createElement('details'),h=document.createElement('summary');h.textContent=a.period+' · 预算 ¥'+money(a.total);d.append(h);for(const t of a.history){const l=document.createElement('div');l.className='ledger';l.textContent=t;d.append(l);}$('#bd-periodhistory').append(d);}if(!state.archives.length)$('#bd-periodhistory').textContent='尚无以往周期';
$('#bd-add').disabled=state.cats.length===1;renderReport();save();
}
function select(id){if(!available(cat(id)))return;selected=selected===id?null:id;if(selected)cut=Math.min(5000,available(cat(id)));render();}
function updateCut(n){if(!selected)return;const c=cat(selected);cut=Math.min(available(c),Math.max(1,Number.isFinite(n)?n:1));$('#bd-slider').value=cut;const field=$('#bd-cutvalue');if(document.activeElement!==field)field.value=cut/100;$('.piece').textContent='¥'+money(cut);$('.cutmark').style.left=(c.budget-cut)/c.budget*100+'%';}
function transfer(id){const from=cat(selected),to=cat(id);if(!from||!to||from===to||!safe(cut)||cut>available(from))return;checkpoint();const n=cut;from.budget-=n;to.budget+=n;const msg=`${from.name} → ${to.name} · ¥${money(n)}`;log(msg);selected=null;render();const target=root.querySelector(`[data-id="${id}"] .dough`);if(!matchMedia('(prefers-reduced-motion: reduce)').matches)target.animate([{transform:'scale(1,.85)'},{transform:'scale(1.04,1.12)'},{transform:'scale(1)'}],{duration:440});notice(msg,true);}
function startDrag(e){if(e.button!==0)return;e.preventDefault();const piece=e.currentTarget;piece.setPointerCapture(e.pointerId);const source=root.querySelector(`[data-id="${selected}"] .track`);const max=Math.max(...state.cats.map(c=>c.budget));const ghost=document.createElement('div');ghost.className='ghost';ghost.style.setProperty('--clay',cat(selected).color);ghost.style.width=Math.max(44,source.clientWidth*cut/max)+'px';ghost.textContent='¥'+money(cut);root.append(ghost);const sourceDough=source.querySelector('.dough'),oldWidth=sourceDough.style.width;sourceDough.style.width=((cat(selected).budget-cut)/max*100)+'%';source.querySelector('.cutmark').hidden=true;drag={ghost,id:e.pointerId,target:null};const move=ev=>{const rect=root.getBoundingClientRect();ghost.style.left=ev.clientX-rect.left+'px';ghost.style.top=ev.clientY-rect.top+'px';const hit=document.elementFromPoint(ev.clientX,ev.clientY)?.closest('.bucket');drag.target=hit&&root.contains(hit)&&hit.dataset.id!==selected?hit.dataset.id:null;root.querySelectorAll('.bucket').forEach(b=>b.classList.toggle('target',b.dataset.id===drag.target));};move(e);piece.onpointermove=move;const finish=ev=>{if(!drag)return;const target=drag.target;ghost.remove();drag=null;piece.onpointermove=null;piece.onpointerup=null;piece.onpointercancel=null;root.querySelectorAll('.target').forEach(b=>b.classList.remove('target'));if(ev.type==='pointerup'&&target)transfer(target);else{sourceDough.style.width=oldWidth;source.querySelector('.cutmark').hidden=false;notice('没有挪动额度，可以重新拖放');}};piece.onpointerup=finish;piece.onpointercancel=finish;}
$('#bd-add').onclick=()=>{$('#bd-expense').hidden=false;$('#bd-category').innerHTML=state.cats.filter(c=>c.id!=='pool').map(c=>`<option value="${c.id}">${esc(c.name)} · 剩余 ¥${money(available(c))}</option>`).join('');$('#bd-expense').scrollIntoView({block:'nearest',behavior:'smooth'});};
$('#bd-expense-submit').onclick=()=>{const c=cat($('#bd-category').value),n=cents($('#bd-cost').value);if(!c||!safe(n)||n>available(c)){$('#bd-expenseerror').textContent='请输入有效金额；余额不足时，请先从其他分类挪入预算。';return;}checkpoint();c.spent+=n;const note=$('#bd-note').value;state.transactions.push({id:'t'+Date.now().toString(36)+Math.random().toString(36).slice(2,7),categoryId:c.id,amount:n,note,recordedAt:new Date().toISOString()});const msg=`${c.name}支出 ¥${money(n)}${note?' · '+note:''}`;log(msg);selected=null;render();$('#bd-cost').value='';$('#bd-note').value='';$('#bd-expense').hidden=true;$('#bd-expenseerror').textContent='';notice(msg,true);};
function hideEditors(){['bd-create','bd-delete','bd-expense','bd-config'].forEach(id=>$('#'+id).hidden=true);}
function openDelete(id){const c=cat(id);if(!c||id==='pool')return;hideEditors();deleting=id;$('#bd-delete').hidden=false;$('#bd-deletemessage').textContent='删除「'+c.name+'」后，剩余 ¥'+money(available(c))+' 回到待分配；已花 ¥'+money(c.spent)+' 和记录保留。';$('#bd-delete').scrollIntoView({block:'nearest'});}
function removeCategory(id){const c=cat(id);if(!c||id==='pool')return;checkpoint();cat('pool').budget+=available(c);if(c.spent)state.deleted.push({id:c.id,name:c.name,spent:c.spent});state.cats=state.cats.filter(x=>x.id!==id);log('删除项目：'+c.name+'；退回 ¥'+money(available(c)));selected=null;hideEditors();render();notice('项目已删除，支出记录保留',true);}
$('#bd-confirmdelete').onclick=()=>removeCategory(deleting);
$('#bd-newcat').onclick=()=>{hideEditors();$('#bd-create').hidden=false;$('#bd-createerror').textContent='';$('#bd-newamount').value='0';$('#bd-create').scrollIntoView({block:'nearest'});$('#bd-newname').focus();};
function addCategory(name,n){name=name.trim();if(!name||name.length>20||state.cats.some(c=>c.name===name)||!Number.isSafeInteger(n)||n<0||n>available(cat('pool')))return false;checkpoint();const colors=['#bfd5a2','#eec285','#c9bee4','#a9cbd8','#e8b7af'];cat('pool').budget-=n;state.cats.splice(state.cats.length-1,0,{id:'c'+Date.now().toString(36)+Math.random().toString(36).slice(2,6),name,budget:n,spent:0,color:colors[state.cats.length%colors.length]});log('新增项目：'+name+' · ¥'+money(n));selected=null;render();notice('已创建「'+name+'」',true);return true;}
function createFromFields(){
const name=$('#bd-newname').value.trim(),raw=$('#bd-newamount').value.trim(),n=raw===''?0:cents(raw),error=$('#bd-createerror');
error.textContent='';
if(!name){error.textContent='请填写项目名称。';$('#bd-newname').focus();return;}
if(name.length>20){error.textContent='项目名称最多 20 个字。';return;}
if(state.cats.some(c=>c.name===name)){error.textContent='已有同名项目，请换一个名称。';return;}
if(!Number.isSafeInteger(n)||n<0){error.textContent='初始额度请输入 0 或正数。';return;}
if(n>available(cat('pool'))){error.textContent='待分配只有 ¥'+money(available(cat('pool')))+'。可以将初始额度设为 0，创建后再从其他项目拖入。';return;}
if(addCategory(name,n)){$('#bd-create').hidden=true;$('#bd-newname').value='';$('#bd-newamount').value='0';const added=state.cats.find(c=>c.name===name);root.querySelector('[data-id="'+added.id+'"]').scrollIntoView({block:'nearest'});}
}
$('#bd-create-submit').onclick=createFromFields;
['bd-newname','bd-newamount'].forEach(id=>$('#'+id).onkeydown=e=>{if(e.key==='Enter'&&!e.isComposing){e.preventDefault();createFromFields();}});
$('#bd-settings').onclick=()=>{hideEditors();showView(false);$('#bd-config').hidden=false;$('#bd-total').value=state.total/100;$('#bd-cycle').value=state.cycle;$('#bd-scope').value='current';$('#bd-allocation').hidden=true;$('#bd-configerror').textContent='';draft=null;};
['bd-total','bd-cycle','bd-scope'].forEach(id=>$('#'+id).oninput=()=>{$('#bd-allocation').hidden=true;draft=null;$('#bd-configerror').textContent='';});
function prepareAllocation(n,isNew,cycle){const spent=isNew?0:state.cats.reduce((a,c)=>a+c.spent,0)+state.deleted.reduce((a,c)=>a+c.spent,0);if(!safe(n)||n<spent)return false;draft={total:n,isNew,cycle,values:{}};state.cats.filter(c=>c.id!=='pool').forEach(c=>draft.values[c.id]=(isNew||n<state.total)?(isNew?0:c.spent):c.budget);return true;}
function allocationStatus(){if(!draft)return;const allocated=Object.values(draft.values).reduce((a,n)=>a+n,0)+(draft.isNew?0:state.deleted.reduce((a,c)=>a+c.spent,0)),remain=draft.total-allocated;$('#bd-allocation-status').textContent=Number.isFinite(remain)?(remain>=0?'待分配 ¥'+money(remain):'超出总预算 ¥'+money(-remain)):'请输入有效额度';$('#bd-saveconfig').disabled=!Number.isFinite(remain)||remain<0;}
function drawAllocation(){const holder=$('#bd-allocation-fields');holder.innerHTML='';for(const c of state.cats.filter(c=>c.id!=='pool')){const label=document.createElement('label'),input=document.createElement('input');input.id='allocation-'+c.id;label.htmlFor=input.id;label.textContent=c.name+(draft.isNew?'':'（已花 ¥'+money(c.spent)+'）');input.type='number';input.min=(draft.isNew?0:c.spent)/100;input.step='0.01';input.value=draft.values[c.id]/100;input.inputMode='decimal';input.oninput=()=>{draft.values[c.id]=input.value===''?NaN:cents(input.value);allocationStatus();};holder.append(label,input);}$('#bd-allocation').hidden=false;allocationStatus();}
$('#bd-nextconfig').onclick=()=>{if(!prepareAllocation(cents($('#bd-total').value),$('#bd-scope').value==='next',$('#bd-cycle').value)){$('#bd-configerror').textContent='当前周期总预算不能低于已经花掉的金额；规划下期请选“新周期”。';return;}$('#bd-configerror').textContent='';drawAllocation();};
$('#bd-clearallocation').onclick=()=>{if(!draft)return;state.cats.filter(c=>c.id!=='pool').forEach(c=>draft.values[c.id]=draft.isNew?0:c.spent);drawAllocation();};
function commitAllocation(){if(!draft)return false;const d=draft,removed=d.isNew?0:state.deleted.reduce((a,c)=>a+c.spent,0);let sum=removed;for(const c of state.cats.filter(c=>c.id!=='pool')){const n=d.values[c.id];if(!Number.isSafeInteger(n)||n<(d.isNew?0:c.spent))return false;sum+=n;}if(sum>d.total)return false;checkpoint();if(d.isNew){const snapshot=JSON.parse(JSON.stringify(state));delete snapshot.archives;state.archives.push(snapshot);state.deleted=[];state.history=[];state.transactions=[];const dt=new Date(state.period.slice(0,7)+'-01T12:00:00Z');if(d.cycle==='month'){dt.setUTCMonth(dt.getUTCMonth()+1);state.period=dt.toISOString().slice(0,7);}else{const wd=new Date(state.period.length===10?state.period+'T12:00:00Z':state.period+'-01T12:00:00Z');wd.setUTCDate(wd.getUTCDate()+7);state.period=wd.toISOString().slice(0,10);}}state.total=d.total;state.cycle=d.cycle;for(const c of state.cats){c.budget=c.id==='pool'?d.total-sum:d.values[c.id];if(d.isNew)c.spent=0;}draft=null;selected=null;log('重新分配预算 ¥'+money(state.total));hideEditors();render();notice('总预算与项目分配已保存',true);if(d.isNew){reportIndex=state.archives.length-1;renderReport();showView(true);}return true;}
$('#bd-saveconfig').onclick=()=>{if(!commitAllocation())$('#bd-configerror').textContent='各项目额度不能低于已花金额，合计不能超过总预算。';};
function periodCats(p){return [...p.cats.filter(c=>c.id!=='pool'),...(p.deleted||[])];}
function categorySpent(p,id){return periodCats(p).filter(c=>c.id===id).reduce((a,c)=>a+c.spent,0);}
function reportData(index){const periods=[...state.archives,state],p=periods[index],prior=periods.slice(0,index).filter(x=>x.cycle===p.cycle),previousPeriod=prior.at(-1),known=new Map();
for(const c of [...periodCats(p),...(previousPeriod?periodCats(previousPeriod):[])])if(!known.has(c.id))known.set(c.id,c);
const rows=[...known.values()].map(c=>{const present=periodCats(p).some(x=>x.id===c.id),amount=categorySpent(p,c.id),past=prior.filter(x=>periodCats(x).some(k=>k.id===c.id)),prevExists=previousPeriod&&periodCats(previousPeriod).some(x=>x.id===c.id),groups=new Map();
for(const t of (p.transactions||[]).filter(t=>t.categoryId===c.id)){const k=t.note.trim()===''?'id:'+t.id:'note:'+t.note;if(!groups.has(k))groups.set(k,{note:t.note,amount:0,entries:[]});const g=groups.get(k);g.amount+=t.amount;g.entries.push(t);}
const detailed=[...groups.values()].reduce((n,g)=>n+g.amount,0),missing=Math.max(0,amount-detailed);
return {id:c.id,name:c.name,present,amount,previous:prevExists?categorySpent(previousPeriod,c.id):null,previousPeriod:previousPeriod?.period,average:past.length>=2?past.reduce((a,x)=>a+categorySpent(x,c.id),0)/past.length:null,samples:past.length,groups:[...groups.values()].sort((a,b)=>b.amount-a.amount),missing};});
return {p,closed:index<state.archives.length,total:periodCats(p).reduce((a,c)=>a+c.spent,0),rows:rows.sort((a,b)=>b.amount-a.amount)};}
function deltaText(value,baseline){if(baseline===null)return '暂无可比数据';const diff=value-baseline;if(Math.abs(diff)<0.00001)return '持平';return (diff>0?'↑ 多花 ':'↓ 少花 ')+'¥'+money(Math.abs(diff))+(baseline>0?'（'+(Math.abs(diff)/baseline*100).toFixed(1)+'%）':'（基准为 0）');}
function showView(report){$('#bd-report').hidden=!report;$('#bd-plan').hidden=report;$('#bd-plan-tab').setAttribute('aria-pressed',String(!report));$('#bd-report-tab').setAttribute('aria-pressed',String(report));}
function renderReport(){const periods=[...state.archives,state];if(reportIndex===null||reportIndex>=periods.length)reportIndex=periods.length-1;const picker=$('#bd-report-period');picker.innerHTML=periods.map((p,i)=>'<option value="'+i+'">'+esc(p.period)+' · '+(p.cycle==='month'?'月':'周')+' · '+(i===periods.length-1?'进行中':'已结束')+'</option>').join('');picker.value=String(reportIndex);const report=reportData(reportIndex),p=report.p;
$('#bd-report-summary').innerHTML='<div class="report-stat">¥'+money(report.total)+'</div><div class="micro">'+(report.closed?'周期实际总支出':'截至目前实际支出 · 周期未结束')+' · 预算 ¥'+money(p.total)+'</div>';
const host=$('#bd-report-items');host.innerHTML='';for(const row of report.rows){const card=document.createElement('section');card.className='report-card';const prevLabel=row.previousPeriod?'对比 '+esc(row.previousPeriod):'对比上一周期';
card.innerHTML='<div class="row"><span class="name">'+esc(row.name)+(row.present?'':'（本期已无此项目）')+'</span><span class="amount">¥'+money(row.amount)+'</span></div><div class="spend-track" style="margin-top:10px"><div style="width:'+(report.total?row.amount/report.total*100:0)+'%"></div></div><div class="comparison">'+prevLabel+'：<span class="'+(row.previous!==null&&row.amount>row.previous?'delta-up':'delta-down')+'">'+deltaText(row.amount,row.previous)+'</span><br>'+(row.previous!==null?'上期支出 ¥'+money(row.previous)+'<br>':'')+(row.average===null?'多期平均：需至少 2 个历史周期（现有 '+row.samples+' 期）':'过去 '+row.samples+' 期平均 ¥'+money(row.average)+'：<span class="'+(row.amount>row.average?'delta-up':'delta-down')+'">'+deltaText(row.amount,row.average)+'</span>')+'</div>';
const details=document.createElement('details');details.open=true;const heading=document.createElement('summary');heading.textContent='具体花在哪儿 · '+(p.transactions||[]).filter(t=>t.categoryId===row.id).length+' 笔记录';details.append(heading);
for(const g of row.groups){const group=document.createElement('details');const title=document.createElement('summary');title.style.whiteSpace='pre-wrap';title.textContent=(g.note.trim()===''?'未填写备注':g.note)+' · ¥'+money(g.amount)+' · '+g.entries.length+' 笔';group.append(title);for(const t of g.entries){const line=document.createElement('div');line.className='detail-row';const label=document.createElement('span'),amount=document.createElement('span');label.textContent='记录时间 '+new Date(t.recordedAt).toLocaleString('zh-CN',{month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'});amount.textContent='¥'+money(t.amount);line.append(label,amount);group.append(line);}details.append(group);}
if(row.missing){const line=document.createElement('div');line.className='micro';line.textContent='旧版未保存的支出明细 ¥'+money(row.missing)+'（总额保留，无法还原备注）';details.append(line);}if(!row.amount){const line=document.createElement('div');line.className='micro';line.textContent='本期没有支出';details.append(line);}card.append(details);host.append(card);}
if(!report.rows.length)host.textContent='还没有项目或支出记录。';}
$('#bd-plan-tab').onclick=()=>showView(false);
$('#bd-report-tab').onclick=()=>{reportIndex=state.archives.length;renderReport();showView(true);};
$('#bd-report-period').onchange=e=>{reportIndex=Number(e.target.value);renderReport();};
function validateData(data){
if(!data||typeof data!=='object'||!Array.isArray(data.archives)||data.archives.length>1000)throw Error('账本结构无效');
for(const p of [...data.archives,data]){
 if(!['month','week'].includes(p.cycle)||!/^\d{4}-\d{2}(-\d{2})?$/.test(p.period)||!Number.isSafeInteger(p.total)||p.total<=0||!Array.isArray(p.cats)||!Array.isArray(p.deleted)||!Array.isArray(p.transactions)||!Array.isArray(p.history))throw Error('周期数据无效');
 if(p.cats.length>200||p.transactions.length>100000)throw Error('账本超过此版本的容量');
 const seen=new Set();for(const c of [...p.cats,...p.deleted]){if(typeof c.id!=='string'||!/^[-a-zA-Z0-9_]{1,100}$/.test(c.id)||seen.has(c.id)||typeof c.name!=='string'||c.name.length>100||!Number.isSafeInteger(c.spent)||c.spent<0)throw Error('项目数据无效');seen.add(c.id);}
 if(p.cats.filter(c=>c.id==='pool').length!==1)throw Error('待分配项目缺失');
 for(const c of p.cats)if(!Number.isSafeInteger(c.budget)||c.budget<c.spent||!/^#[a-fA-F0-9]{6}$/.test(c.color))throw Error('项目额度无效');
 if(p.cats.reduce((n,c)=>n+c.budget,0)+p.deleted.reduce((n,c)=>n+c.spent,0)!==p.total)throw Error('总预算与项目额度不符');
 const ids=new Set();for(const t of p.transactions){if(typeof t.id!=='string'||ids.has(t.id)||!seen.has(t.categoryId)||t.categoryId==='pool'||!Number.isSafeInteger(t.amount)||t.amount<=0||typeof t.note!=='string'||t.note.length>1000||!Number.isFinite(Date.parse(t.recordedAt)))throw Error('支出记录无效');ids.add(t.id);}
 for(const c of [...p.cats,...p.deleted])if(p.transactions.filter(t=>t.categoryId===c.id).reduce((n,t)=>n+t.amount,0)>c.spent)throw Error('明细合计超过支出总额');
 if(p.history.some(t=>typeof t!=='string'))throw Error('操作记录无效');
}return true;}
function backupData(){return {app:'rouqian-web',version:1,exportedAt:new Date().toISOString(),data:state};}
function restoreBackup(raw){const file=JSON.parse(raw);if(file.app!=='rouqian-web'||file.version!==1)throw Error('请选择揉钱网页版导出的备份');validateData(file.data);return file.data;}
$('#bd-export').onclick=()=>{const text=storageBlocked?(localStorage.getItem(key)||JSON.stringify(backupData(),null,2)):JSON.stringify(backupData(),null,2);const blob=new Blob([text],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='rouqian-backup-'+new Date().toISOString().slice(0,10)+'.json';document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),30000);notice('备份已生成，请在下载列表或“文件”中确认保存。');};
$('#bd-import').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>5*1024*1024)throw Error('备份不能超过 5 MB');const next=restoreBackup(await file.text());if(!confirm('恢复备份将替换当前设备的账本。建议先导出当前数据。继续恢复？'))return;localStorage.setItem(key,JSON.stringify(next));previous=JSON.parse(JSON.stringify(state));state=next;storageBlocked=false;canStore=true;selected=null;reportIndex=null;hideEditors();render();notice('账本已恢复',true);}catch(err){notice('恢复失败：'+err.message);}finally{e.target.value='';}};
window.addEventListener('storage',e=>{if(e.key===key&&e.newValue){try{const p=JSON.parse(e.newValue);validateData(p);state=p;previous=null;selected=null;reportIndex=null;hideEditors();render();notice('已载入另一个窗口保存的账本');}catch{notice('另一个窗口的数据异常，请导出备份。');}}});
if('serviceWorker' in navigator&&location.protocol!=='file:')navigator.serviceWorker.register('./sw.js').then(()=>navigator.serviceWorker.ready).then(()=>{$('#bd-offline').textContent='离线缓存已准备；首次安装到主屏幕后请联网打开一次。';}).catch(()=>{$('#bd-offline').textContent='离线缓存暂不可用，仍可联网使用。';});else $('#bd-offline').textContent='请通过 GitHub Pages 的 HTTPS 链接使用安装与离线功能。';
root.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>$('#'+b.dataset.close).hidden=true);render();notice('长按彩色额度，或点「切一块」开始。');
})();
